#!/usr/bin/env ruby

require 'erb'

PAGES_DIR = "pages"
ASSETS_DIR = "assets"
GENERATED_DIR = "generated"
WRAPPER = "wrapper.html.erb"

def file_contents(fname)
  File.open(fname, 'rb') { |f| f.read }
end

class Page
  def self.wrapper
    @wrapper ||= ERB.new(file_contents(WRAPPER))
  end
  def initialize(fname)
    @infile_name = fname
    @inner_contents = file_contents(fname)
  end
  attr_reader :inner_contents
  def outfile_name
    File.join(GENERATED_DIR, File.basename(@infile_name))
  end
  def outfile_contents
    self.class.wrapper.result(binding)
  end
  def generate!
    File.open(outfile_name, 'w') {|f| f.write(outfile_contents) }
  end
end

Dir.foreach(PAGES_DIR) do |fname|
  fname = File.join(PAGES_DIR, fname)
  if File.file?(fname)
    Page.new(fname).generate!
  end
end

`cp #{ASSETS_DIR}/* #{GENERATED_DIR}`
